app_name: 'leihs-{{leihs_sync_name}}-sync'
app_user: '{{app_name}}'
app_dir: '/{{app_name}}'
config_file: '{{inventory_dir}}/config/{{leihs_sync_name}}_sync-config.yml'
config_file_target: '/etc/leihs/{{app_name}}.yml'
