- name: make sure `/etc/leihs/' exists
  file:
    path: /etc/leihs/
    state: directory
    mode: '0755'

- name: install config
  template:
    src: '{{config_file}}'
    dest: '{{config_file_target}}'
    mode: 0640
    owner: root
    group: '{{app_user}}'

