- name: make sure `/etc/leihs/' exists
  file:
    path: /etc/leihs/
    state: directory
    mode: '0755'

- name: install config
  template:
    src: '{{config_file}}'
    dest: '{{config_file_target}}'
    mode: 0600
    owner: '{{app_user}}'
    group: '{{app_user}}'
