- name: create uberjar
  delegate_to: localhost
  args:
    executable: /bin/bash
  shell: |
    #!/usr/bin/env bash
    set -euxo
    cd {{playbook_dir}}/..
    ./bin/clj-uberjar

- name: copy uberjar
  copy:
    src: '{{playbook_dir}}/../leihs-sync.jar'
    dest: '{{app_dir}}/leihs-sync.jar'
    owner: '{{app_user}}'
