- name: create uberjar
  delegate_to: localhost
  run_once: true
  args:
    executable: /bin/bash
  shell: |
    #!/usr/bin/env bash
    set -euo pipefail
    cd {{local_leihs_sync_dir}}
    ./bin/clj-uberjar

- name: copy uberjar
  copy:
    src: '{{role_path}}/../../../leihs-sync.jar'
    dest: '{{app_dir}}/leihs-sync.jar'
    owner: '{{app_user}}'
